// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwDNZMdIEMciEDyS0oPVlbPmpamLLvPQ',
    appId: '1:549644688547:web:de2a05075eefb93ecf7316',
    messagingSenderId: '549644688547',
    projectId: 'daily-fusion',
    authDomain: 'daily-fusion.firebaseapp.com',
    storageBucket: 'daily-fusion.firebasestorage.app',
    measurementId: 'G-S0H41L3NW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkuRVhc8It6-SLaXoPNnGRim-zJeyxO5E',
    appId: '1:549644688547:android:13f9739a24244ff7cf7316',
    messagingSenderId: '549644688547',
    projectId: 'daily-fusion',
    storageBucket: 'daily-fusion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2em4S-rxX8-Z85y566AuoXVxUqG5Oi9E',
    appId: '1:549644688547:ios:f9e0835e98e9c6cfcf7316',
    messagingSenderId: '549644688547',
    projectId: 'daily-fusion',
    storageBucket: 'daily-fusion.firebasestorage.app',
    iosClientId: '549644688547-fa7u1mllgu64gpv6p93tmftcia5otnko.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2em4S-rxX8-Z85y566AuoXVxUqG5Oi9E',
    appId: '1:549644688547:ios:f9e0835e98e9c6cfcf7316',
    messagingSenderId: '549644688547',
    projectId: 'daily-fusion',
    storageBucket: 'daily-fusion.firebasestorage.app',
    iosClientId: '549644688547-fa7u1mllgu64gpv6p93tmftcia5otnko.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyfusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYwDNZMdIEMciEDyS0oPVlbPmpamLLvPQ',
    appId: '1:549644688547:web:fd3f23c264f6ede7cf7316',
    messagingSenderId: '549644688547',
    projectId: 'daily-fusion',
    authDomain: 'daily-fusion.firebaseapp.com',
    storageBucket: 'daily-fusion.firebasestorage.app',
    measurementId: 'G-6FD31S367H',
  );
}
